### ISSUE TITLE
Error : First argument contains NaN in property 'rotation'

### ISSUE THREAD

**Issue by GatoAdmin** [vicberg/CombatMaster#7]
`Error: Firebase.update failed: First argument contains NaN in property 'rotation'
Error: Firebase.update failed: First argument contains NaN in property 'rotation'
    at Ba (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:9:186)
    at Ba (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:10:207)
    at Aa (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:8:462)
    at Ea (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:10:403)
    at J.update (/home/node/d20-api-server/node_modules/firebase/lib/firebase-node.js:146:318)
    at TrackedObj._doSave (/home/node/d20-api-server/api.js:905:27)
    at Timeout.later [as _onTimeout] (/home/node/d20-api-server/node_modules/underscore/underscore-umd.js:1153:39)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)`

I traker this error that in animateActiveTokenMarker function line 1986

`let rotation_duration  = 1000 * parseInt(state[combatState].config.turnorder.animateMarkerDuratio);`
is change to
`let rotation_duration  = 1000 * parseInt(state[combatState].config.turnorder.animateMarkerWait);`

it error clear.

please this code fix

**Comment by vicberg** [comment]
It's fixed in my github.  Grab latest.
